name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [22.10.0]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Trigger Redeploy API
      run: |
        curl -X POST https://generate.api.devtrend.tech \
        -H "Content-Type: application/json" \
        -d '{"secret_key": "${{ secrets.REDEPLOY_SECRET }}"}'