name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      
    - name: Trigger Git Fetch
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy_nextjs_blog/git_fetch \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}"}'
        
    - name: Trigger Git Reset
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy_nextjs_blog/git_reset \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}"}'
        
    - name: Trigger NPM Install
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy_nextjs_blog/npm_install \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}"}'
        
    - name: Trigger NPM Build
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy_nextjs_blog/npm_build \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}"}'
        
    - name: Trigger PM2 Reload
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy_nextjs_blog/pm2_reload \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}"}'