name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      
    - name: Trigger Git Fetch
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy-nextjs-blog/execute \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}", "command": "git fetch origin || exit"}'

    - name: Reset to Main
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy-nextjs-blog/execute \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}", "command": "git reset --hard origin/main || exit"}'

    - name: Install Dependencies
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy-nextjs-blog/execute \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}", "command": "npm install"}'

    - name: Build & Deploy the new release
      run: |
        curl -X POST https://deploy.api.devtrend.tech/deploy-nextjs-blog/execute \
        -H "Content-Type: application/json" \
        -d '{"redeploy_secret": "${{ secrets.REDEPLOY_SECRET }}", "command": "chmod +x redeploy.sh && ./redeploy.sh || exit"}'